# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [442]:
# 載入 NumPy 套件
import numpy as np

# 檢查正確載入與版本
print(np)
print(np.__version__)


<module 'numpy' from 'C:\\Users\\Justin\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>
1.19.2


In [443]:
# 從一個陣列開始

a = np.arange(15).reshape(3, 5)
print(a) # 利用 print(...) 印出陣列
a # 利用 Jupyter 印出陣列

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [444]:
# 陣列的常用屬性

print('ndim: ', a.ndim)
print('shape: ', a.shape)
print('size: ', a.size)
print('dtype: ', a.dtype)
print('itemsize: ', a.itemsize)
print('data: ', a.data)
'''
ndarray.ndim： 陣列有多少維度
ndarray.shape： 每個維度的大小
ndarray.size： 陣列當中有幾個元素
ndarray.dtype： 陣列中的資料型態
ndarray.itemsize： 陣列中每個元素佔用的空間
ndarray.data： 陣列所存在的記憶體位置'''

ndim:  2
shape:  (3, 5)
size:  15
dtype:  int32
itemsize:  4
data:  <memory at 0x0000016C588DDBA0>


'\nndarray.ndim： 陣列有多少維度\nndarray.shape： 每個維度的大小\nndarray.size： 陣列當中有幾個元素\nndarray.dtype： 陣列中的資料型態\nndarray.itemsize： 陣列中每個元素佔用的空間\nndarray.data： 陣列所存在的記憶體位置'

In [445]:
'''
Your Code
'''
print('list(a): ', list(a))
print('a.tolist(): ', a.tolist())

# 從一個陣列開始
b = np.arange(15).reshape(1, 15)
print(b) # 利用 print(...) 印出陣列

print('list(b): ', list(b))
print('b.tolist(): ', b.tolist())

print("list()：只有第一層轉成list，第二層還是維持array")
print(".list()方法：每一層都轉成list")

list(a):  [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]
a.tolist():  [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]
list(b):  [array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])]
b.tolist():  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]]
list()：只有第一層轉成list，第二層還是維持array
.list()方法：每一層都轉成list


### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [446]:
# 記得先 Import 正確的套件
# 載入 NumPy 套件
'''
Your Code
'''
import numpy as np


In [447]:
a = np.random.randint(10, size=6) 
'''
Your Code
'''
print('ndim: ', a.ndim)
print('shape: ', a.shape)
print('size: ', a.size)
print('dtype: ', a.dtype)
print('itemsize: ', a.itemsize)
print('data: ', a.data)
print('length: ', len(a.tolist()))
print('type: ', type(b))
print('type(a.tolist()): ', type(a.tolist()))
print('type(list(a))', type(list(a)))


ndim:  1
shape:  (6,)
size:  6
dtype:  int32
itemsize:  4
data:  <memory at 0x0000016C58A3AE80>
length:  6
type:  <class 'numpy.ndarray'>
type(a.tolist()):  <class 'list'>
type(list(a)) <class 'list'>


In [448]:
b = np.random.randint(10, size=(3,4)) 

'''
Your Code
'''
print('ndim: ', b.ndim)
print('shape: ', b.shape)
print('size: ', b.size)
print('dtype: ', b.dtype)
print('itemsize: ', b.itemsize)
print('data: ', b.data)
print('length: ', len(b.tolist()))
print('type: ', type(b))
print('type(b.tolist()): ', type(b.tolist()))
print('type(list(b))', type(list(b)))

ndim:  2
shape:  (3, 4)
size:  12
dtype:  int32
itemsize:  4
data:  <memory at 0x0000016C588DDBA0>
length:  3
type:  <class 'numpy.ndarray'>
type(b.tolist()):  <class 'list'>
type(list(b)) <class 'list'>


In [449]:
c = np.random.randint(10, size=(2,3,2)) 

'''
Your Code
'''
print('ndim: ', c.ndim)
print('shape: ', c.shape)
print('size: ', c.size)
print('dtype: ', c.dtype)
print('itemsize: ', c.itemsize)
print('data: ', c.data)
print('length: ', len(c.tolist()))
print('type: ', type(c))
print('type(b.tolist()): ', type(c.tolist()))
print('type(list(c))', type(list(c)))

ndim:  3
shape:  (2, 3, 2)
size:  12
dtype:  int32
itemsize:  4
data:  <memory at 0x0000016C59A90D60>
length:  2
type:  <class 'numpy.ndarray'>
type(b.tolist()):  <class 'list'>
type(list(c)) <class 'list'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。(難度較高)

In [450]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[3, 3, 8, 1, 8, 0]
[3, 3, 8, 1, 8, 0]


In [451]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[8, 6, 0, 0], [4, 1, 7, 3], [6, 7, 0, 0]]
[array([8, 6, 0, 0]), array([4, 1, 7, 3]), array([6, 7, 0, 0])]


In [452]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[2, 6], [2, 1], [8, 6]], [[3, 9], [6, 4], [0, 0]]]
[array([[2, 6],
       [2, 1],
       [8, 6]]), array([[3, 9],
       [6, 4],
       [0, 0]])]


In [453]:
##簡單版

def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    newlist=[]
    for obj in iterable:
        newlist.append(tolist(obj))
    return list(newlist)
        
    
    
print(tolist(a))
print(tolist(b))
print(tolist(c))

[3, 3, 8, 1, 8, 0]
[[8, 6, 0, 0], [4, 1, 7, 3], [6, 7, 0, 0]]
[[[2, 6], [2, 1], [8, 6]], [[3, 9], [6, 4], [0, 0]]]


In [454]:
##進階版

def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    return [tolist(obj) for obj in iterable]
            
print(tolist(a))
print(tolist(b))
print(tolist(c))

[3, 3, 8, 1, 8, 0]
[[8, 6, 0, 0], [4, 1, 7, 3], [6, 7, 0, 0]]
[[[2, 6], [2, 1], [8, 6]], [[3, 9], [6, 4], [0, 0]]]
